version: "3.8"

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    depends_on:
      - react_frontend

  react_frontend:
    build: ./react_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true